test

diff --git a/.github/workflows/truffleHog.yml b/.github/workflows/truffleHog.yml
--- a/.github/workflows/truffleHog.yml
+++ b/.github/workflows/truffleHog.yml
@@ -1,10 +1,22 @@
-name: Leaked Secrets Scan
+name: TruffleHog Secrets Scan
 on: [push]
 jobs:
   TruffleHog:
     runs-on: ubuntu-latest
+    container:
+      image: trufflesecurity/trufflehog:latest
     steps:
-      - uses: actions/checkout@v2
-      - uses: UnicornGlobal/trufflehog-actions-scan@master
-        with:
-          branch: ${{ github.head_ref }}
+      - uses: actions/checkout@v3
+      - name: Checkout code test 1111
+        continue-on-error: true
+        run: |
+          rm -rf /__w/trufflehogtest/trufflehogtest/.git
+          trufflehog filesystem /__w/trufflehogtest/trufflehogtest --no-verification --no-update --fail
+          if [ $? -eq 183 ]; then echo "error   2222222222222222" && exit 1; fi
+      - name: send msg
+        if: steps.trufflehog.outcome == 'failure'
+        run: |
+          echo "error   876868767878608760876"
+      - name: send msg 34
+        run: |
+          echo "error   333333"
